language: go

go:
  - 1.x

install:
  - go get github.com/mattn/go-runewidth
  - go get github.com/nsf/termbox-go
  - go get golang.org/x/lint/golint

script:
  - go test -v -race ./...
  - golint -set_exit_status ./...
